name: assessment
description: "Assessment Test App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  path_provider: ^2.1.4
  flutter_screenutil: ^5.9.3
  get_it: ^7.6.7
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.5
  go_router: ^13.2.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  meta: ^1.10.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/stackbuld.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/png/stackbuld.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/png/stackbuld.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/png/stackbuld.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/ico/
